apiVersion: v1
entries:
  postgresql:
  - annotations:
      category: Database
    apiVersion: v2
    appVersion: 11.13.0
    created: "2022-02-10T09:46:21.1022303+01:00"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      version: 1.x.x
    description: Chart for PostgreSQL, an object-relational database management system (ORDBMS) with an emphasis on extensibility and on standards-compliance.
    digest: 1b7c4bfba1e8257793e8d6690e02b86c0bdac99922e1fa74b6a7df9d800938ab
    home: https://github.com/bitnami/charts/tree/master/bitnami/postgresql
    icon: https://bitnami.com/assets/stacks/postgresql/img/postgresql-stack-220x234.png
    keywords:
    - postgresql
    - postgres
    - database
    - sql
    - replication
    - cluster
    maintainers:
    - email: containers@bitnami.com
      name: Bitnami
    - email: cedric@desaintmartin.fr
      name: desaintmartin
    name: postgresql
    sources:
    - https://github.com/bitnami/bitnami-docker-postgresql
    - https://www.postgresql.org/
    urls:
    - charts/postgresql-10.10.3.tgz
    version: 10.10.3
  redis:
  - annotations:
      category: Database
    apiVersion: v2
    appVersion: 6.2.5
    created: "2022-02-10T09:46:21.1072304+01:00"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      tags:
      - bitnami-common
      version: 1.x.x
    description: Open source, advanced key-value store. It is often referred to as a data structure server since keys can contain strings, hashes, lists, sets and sorted sets.
    digest: f8fa3b0bdaecf7f9aa1669b027c5452f7efaab21c10b0dbcf7148e17c54ac5b7
    home: https://github.com/bitnami/charts/tree/master/bitnami/redis
    icon: https://bitnami.com/assets/stacks/redis/img/redis-stack-220x234.png
    keywords:
    - redis
    - keyvalue
    - database
    maintainers:
    - email: containers@bitnami.com
      name: Bitnami
    - email: cedric@desaintmartin.fr
      name: desaintmartin
    name: redis
    sources:
    - https://github.com/bitnami/bitnami-docker-redis
    - http://redis.io/
    urls:
    - charts/redis-15.3.2.tgz
    version: 15.3.2
  taalhuizen-logic:
  - annotations:
      artifacthub.io/containsSecurityUpdates: "true"
    apiVersion: v2
    appVersion: V1.0
    created: "2022-02-10T09:46:21.0977331+01:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.1.1
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 12.7.7
    description: Het Proto Component vormt zowel de gemeenschappelijke basis onder alle componenten, als een “template” voor het maken van nieuwe componenten.
    digest: cbac082a92d622d3e1c1c87a9bdc0ef507514fcbccf801d2a9d0bbaad3ae9c60
    home: https://www.conduction.nl
    icon: https://conductionnl.github.io/images/conduction_avatar_blue_on_transparant.svg
    keywords:
    - commonground
    - haven
    - nlx
    - component
    maintainers:
    - email: ruben@conduction.nl
      name: Ruben van der Linde
    - email: info@conduction.nl
      name: Conduction
    name: taalhuizen-logic
    sources:
    - https://commonground.conduction.nl/
    - https://www.commonground.nl/
    urls:
    - taalhuizen-logic-1.0.0.tgz
    version: 1.0.0
generated: "2022-02-10T09:46:21.0527316+01:00"
