apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Chart.Name }}-participation-status
  labels:
    {{- include "template.labels" . | nindent 4 }}
spec:
  # this cronjob runs every night at 03:00 https://crontab.guru/#*_*_*_*_*
  schedule: "0 3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
          - name: dependencies
            secret:
              secretName: {{ .Chart.Name }}-dependencies
              defaultMode: 420
          containers:
          - name: {{ .Chart.Name }}-php
            image: "{{ .Values.php.repository }}:{{ .Values.php.tag | default .Chart.AppVersion }}"
            imagePullPolicy: Always
            args:
            - bin/console 
            - app:participations:status
            volumeMounts:
              - mountPath: /srv/api/config/packages/dependencies.yaml
                subPath: dependencies.yaml
                name: dependencies
                readOnly: true
            env:
              - name: JWT_SECRET_KEY
                value: '%kernel.project_dir%/config/jwt/private.pem'
              - name: JWT_PUBLIC_KEY
                value: '%kernel.project_dir%/config/jwt/public.pem'
              - name: JWT_PASSPHRASE
                value: 'bafe1dc254b45471754c221081f874aa'
              - name: APP_ENV
                value: 'prod'
              - name: TRUSTED_HOSTS
                valueFrom:
                  configMapKeyRef:
                    name: {{ .Chart.Name }}
                    key: trusted-hosts
              - name: TRUSTED_PROXIES
                valueFrom:
                  configMapKeyRef:
                    name: {{ .Chart.Name }}
                    key: trusted-proxies
              - name: APP_VERSION
                valueFrom:
                  configMapKeyRef:
                    name: {{ .Chart.Name }}
                    key: app-version
              - name: APP_DEBUG
                valueFrom:
                  configMapKeyRef:
                    name: {{ .Chart.Name }}
                    key: debug
              - name: APP_CACHE
                valueFrom:
                  configMapKeyRef:
                    name: {{ .Chart.Name }}
                    key: cache
              - name: DATABASE_URL
                valueFrom:
                  secretKeyRef:
                    name: {{ .Chart.Name }}
                    key: database-url
              - name: CORS_ALLOW_ORIGIN
                valueFrom:
                  configMapKeyRef:
                    name: {{ .Chart.Name }}
                    key: app-corsAllowOrigin
              - name: APP_APPLICATION_KEY
                valueFrom:
                  secretKeyRef:
                    name: {{ .Chart.Name }}
                    key: app_application_key
              {{ if .Values.redis.enabled }}
              - name: REDIS_HOST
                valueFrom:
                  configMapKeyRef:
                    name: {{ .Chart.Name }}
                    key: redis-host
              - name: REDIS_PORT
                valueFrom:
                  configMapKeyRef:
                    name: {{ .Chart.Name }}
                    key: redis-port
              {{- end }}
              - name: APP_URL
                valueFrom:
                  configMapKeyRef:
                    key: url
                    name: {{ .Chart.Name }}
          restartPolicy: OnFailure
